FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

#RUN mkdir Otm 
#RUN mkdir Snap7 

# Copy everything else and build
COPY . ./

RUN ls -la ./
RUN dotnet publish ./Otm/Otm.csproj -c Release -o out

# restore project
RUN dotnet restore ./Otm/Otm.csproj
RUN dotnet restore ./Snap7/Snap7.csproj

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "otm.dll"]

